[tool.poetry]
name = "farm"
version = "0.1.0"
description = ""
authors = ["Jake Bayley <jake@entia.co>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
