name: Farm CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./farm

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
          poetry-version: 1.0.10

    - name: Cache Poetry virtualenv
      working-directory: ${{env.working-directory}}
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Set Poetry config
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install Dependencies
      working-directory: ${{env.working-directory}}
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Code Quality
      working-directory: ${{env.working-directory}}
      run: poetry run black . --check

    - name: Test with pytest
      working-directory: ${{env.working-directory}}
      run: poetry run pytest
